apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.carleton-masprod.carleton.ca:6443
  name: api-carleton-masdev-carleton-ca:6443
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.carleton-masprod.carleton.ca:6443
  name: api-carleton-masprod-carleton-ca:6443
contexts:
- context:
    cluster: api-carleton-masdev-carleton-ca:6443
    namespace: mas-masdev-manage
    user: kube:admin/api-carleton-masdev-carleton-ca:6443
  name: mas-masdev-manage/api-carleton-masdev-carleton-ca:6443/kube:admin
- context:
    cluster: api-carleton-masprod-carleton-ca:6443
    namespace: mas-masprod-manage
    user: kube:admin/api-carleton-masprod-carleton-ca:6443
  name: mas-masprod-manage/api-carleton-masprod-carleton-ca:6443/kube:admin
current-context: mas-masprod-manage/api-carleton-masprod-carleton-ca:6443/kube:admin
kind: Config
preferences: {}
users:
- name: kube:admin/api-carleton-masdev-carleton-ca:6443
  user:
    token: sha256~Y1exMmJfgW4p8yfMJQX0gSWnYSvfXhtxQ-Dkc3XBZa4
- name: kube:admin/api-carleton-masprod-carleton-ca:6443
  user: {}
